### ISSUE TITLE
209A: Test Case 1.2 - Addenda not working, Complaint Page 1, Box J(5)

### ISSUE THREAD

**Issue by kateleebarry** [SuffolkLITLab/docassemble-MA209AProtectiveOrder#19]
The test's instruction was to: "Enter A LOT of text in the 'This is why the judge should order [defendant] to pay me' field (we want to see what happens if an excessive amount of text is entered into this field and how it shows up on the pdf form)"

The appropriate box on the 209A Complaint Page 1 was blank.  The addenda did trigger but there was not any text on it.  See: https://drive.google.com/file/d/1yQ9N7n6lzP7aUlK-DEYGyYkZunc55_VT/view?usp=sharing

**Comment by purplesky2016** [comment]
Should I pull the master branch?

How do I run the interview?

**Comment by nonprofittechy** [comment]
This is probably out of date--i just transferred a bunch of issues over

**Comment by purplesky2016** [comment]
Please tell me which branch of code I should use, and which yml file will start the interview.

**Comment by purplesky2016** [comment]
Or maybe you meant that these messages are out of date so I am not currently "assigned" to the issue?

**Comment by nonprofittechy** [comment]
I don't think this is actually a problem anymore. i think we just forgot to close the issue. You got a notification because I transferred it to a new repository

**Comment by purplesky2016** [comment]
Great. Thanks!

**Comment by CaroRob** [comment]
The field is limited to 113 characters - so we are not using an addendum.
