### ISSUE TITLE
209A Test Case 1.7: Addenda not working Complaint Page 1, Question J(8)

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MA209AProtectiveOrder#20]
# Survey result on row 94

**Report type:** A test case (qa)

**Contact info**: Aubrie - slack 

---

### Bug

Question | Answer
---|---
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Question** | 
**Confusion** | 
**Feedback** | 

---

### Something else

Uncategorized Feedback:

---

### Test report

Question | Answer
---|---
**Link to spreadsheet** | https://docs.google.com/spreadsheets/d/1EMtbq4tiUWXh0dR8HwWu_nEuMyqRBsY6ShGDk-782ks/edit#gid=1836369613&range=AQ11
**Test id** | 209A Test ID 1.7 
**Tester** | aubreisouza
**Question** | " I also need the judge to order..."
**Input** | Tested this twice - Entered the following text 3 times, additionally tried hand typing until it seemed excessive - "Enter A LOT of text in the 'I also need the judge to order' field (we want to see what happens if an excessive amount of text is entered into this field and how it shows up on the pdf form)" x3 into the explination
**Expected** | Show text on final document
**Actual** | I am not finding the text anywhere on the 209A generated - an addendum is generated for Part J(8) Other order requested, but it has no inofrmation.  I am not sure if this is where it would appear, but that it my educated guess. I'm attaching my second run pdf with the above text in addition ot the PDF that is on the spreadsheet
**Link** | Not seeing link
**Pic** | https://drive.google.com/open?id=1Uxb2GzRMxh0gSFT41ZpSPe5rBHQ6Hkpg
**Notes** | n/a

**Error message**
```
n/a
```

---

### Thank you!

**Comment by CaroRob** [comment]
Field J8 on Page 1 is limited to 200 characters, and does not create an addendum.
