### ISSUE TITLE
209A_defendant-information.yml - id: defendant vital stats

### ISSUE THREAD

**Issue by CaroRob** [SuffolkLITLab/docassemble-MA209AProtectiveOrder#46]
when putting a '+' sign in  field other_parties[0].physical_other_details, no error, but interview will not progress, gets stuck on same question.

**Comment by CaroRob** [comment]
actually, entering **anything ** in this field prevents interview from progressing.

**Comment by plocket** [comment]
Note for future us - is it possible that this change in the code has contributed to a bit of this issue? https://github.com/SuffolkLITLab/docassemble-MA209AProtectiveOrder/issues/20#issuecomment-652459970

**Comment by CaroRob** [comment]
@plocket 
I think Lily's comment in issue #20 was misplaced. Reasons for no contact should be in the context of plaintiff giving judge reasons why defendant should be ordered not to have contact with children, which would be page 2 of the of the complaint and nothing to do with other orders plaintiff is requesting the judge to make - which is the issue in #20.

As for this issue - defendant information, the problem I think is that if one puts a '+' sign into the variable other_parties[0].physical_other_details, the validation code cannot read and gets stuck.  If you change the value without refreshing the screen, you cannot progress to the next screen. If you refresh the screen and put in text that does not have a '+' symbol in, you can go further.

I thought we @plocket  and I, experimented with various permutations, yesterday. We even commented out the validation code,**but** we were using the review screens which have their own unique influences. 

To solve the first bug - we have to fix validation code, when I comment it out, the screen progresses, although it didn't appear to progress yesterday, today it does.
```
# validation code: |
#   if len(other_parties[0].physical_other_details) > (88 - len(str(other_parties[0].physical_other.true_values()))):
#    validation_error("There is only space for " + str((88 - len(str(other_parties[0].physical_other.true_values())))) + " more characters on the form.", field= 'other_parties[0].physical_other_details')

```
Is it possible to allow users to include special characters in validation code or, do we have to ask users not to use them?
This bug makes me think we must have the same problem in id: locating defendant which adds up the length of the characters in fields to limit character length in last field:
```
`validation code: |
  if len(other_parties[0].location_information_other) > (675 - len(str(other_parties[0].location_best + other_parties[0].best_times_find + other_parties[0].locations_other))):
    validation_error("There is only space for " + str((675 - len(str(other_parties[0].location_best + other_parties[0].best_times_find + other_parties[0].locations_other)))) + " more characters on the form.", field='other_parties[0].location_information_other')`
```

**Nope!,** validation code in  id: locating defendant works if I put '+' sign into location_best, or  locations_other

Cannot figure out what to test anymore.

**Comment by plocket** [comment]
I couldn't replicate this behavior. [Video of what I did from defendant questions onwards](https://drive.google.com/file/d/1vLNXpvAYQnza0DQFf1eIWQqKc3rnwZy5/view?usp=sharing). Will edit to add variable values in here too.

**Comment by plocket** [comment]
Closing this for now till we can replicate behavior. Everyone record yourselves going through the interview!
