### ISSUE TITLE
User: bug

### ISSUE THREAD

**Issue by suffolklitlab-issues** [SuffolkLITLab/docassemble-MA209AProtectiveOrder#60]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `has school address`
Steps to reproduce | Clicked that I currently attend school and tried to fill in mandatory field for name of school
Expected behavior | Expected to be able to fill in name of school
What happened instead | It wouldn't let me type any characters.  Tried it on two different computers.
Other information | This is Kate
Variable being sought | `users[0].schools.target_number`
Package version | `1.0.20`

**Comment by kateleebarry** [comment]
Never mind, I wasn't really reading the question. It was asking for number of schools, not name of school.
