### ISSUE TITLE
${children.did_verb('was')} is not conjugating correctly if minor plaintiff is responsible for minor children

### ISSUE THREAD

**Issue by CaroRob** [SuffolkLITLab/docassemble-MA209AProtectiveOrder#67]
Preventing me from doing a PR on branches

- AdvocateImprovements-with-intermediate-variable and
- AdvocateImprovements1

children.as_noun() **works** if plaintiff is responsible for minor children, that is the variable displays child or children correctly.
But children.did_verb('was') is always singular even if plaintiff is responsible for more than one child. 

The situation is unlikely to occur, but we still need to account if minor plaintiff has no children of their own, but is responsible for children. 

I am not sure what happens if plaintiff has one child of their own and one child they are responsible for. - children should be plural and so should the verb.
I think I tested with just children of their own, not responsible for children and the variable for the verb does work.

We use this in the Affidavit yml.

I think the code for this probably has to go in page2.yml
but we use it in almost all the questions in the Affidavit.yml that ask about children
See: id: 209 Affidavit what to include

I think this is the reason I didn't commit my branch

**Comment by plocket** [comment]
Do commit your branch - committing the branch won't do any harm, it'll let us better see what you're describing and let us work on your work directly. We can always improve the branch with more commits.

I may talk to you live to confirm I'm understanding your description here.

**Comment by plocket** [comment]
Closed by #75 I assume. Can reopen if that's not true.
