### ISSUE TITLE
Is it worth it/timely to rename the attachment files?

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-MA209AProtectiveOrder#72]
What do you think, @plocket @CaroRob?

As I keep working in the attachments to finish the migration up, I think it would make sense to make the filenames consistent with the attachment names inside the YAML.

My main approach is to use GL209A_ as the prefix (so it is a valid variable name) and then something very short.

Renaming the attachments requires everyone to create a new Docassemble project and do a new git pull, otherwise Docassemble will clobber the list of attachments.

**Comment by plocket** [comment]
Love cleaning up names and I make new projects like they're on sale, so this sounds good to me.
