### ISSUE TITLE
Missing PDF variable attribute

### ISSUE THREAD

**Issue by BryceStevenWilley** [SuffolkLITLab/docassemble-MA209AProtectiveOrder#92]
On the production server:
```
DAErrorMissingVariable: 

    Interview has an error.  There was a reference to a variable 'kPcqMbhwIWwn.pdf' that could not be looked up in the question file (for language 'en') or in any of the files incorporated by reference into the question file.
    
The referer URL was https://apps.suffolklitlab.org/run/209a/
```
The random name here is definitely a DAObject that isn't named: DAObjects that aren't given specific names (through the objects block) are given random names. The PDF attribute likely means that it's something to do with the ALDocument.

**Comment by plocket** [comment]
Not sure I even have a login there. Do we know what commit it's on?

**Comment by BryceStevenWilley** [comment]
Sorry, that would have been good to have: it's version `2.0.3`, don't have the specific commit.

**Comment by plocket** [comment]
Is it broken for all production server interviews or just under certain circumstances? It looks like something that would always error. If so, should we disable the interview or does it error on the first page? Otherwise users will do all the work and not get the final result, right?

**Comment by nonprofittechy** [comment]
@plocket the context here is that we get an email copy of errors on the production server. Bryce doesn't have any context for the error other than that it happened and the message he pasted on the issue. Someone will need to investigate and get an answer to some of those questions. But probably the same person who investigates it can fix it. This isn't a good thread to raise questions on.

**Comment by plocket** [comment]
To catch this issue up, I went through to the end on the production server with no errors. I also used the sharable link in an incognito window with no errors: https://apps.suffolklitlab.org/goto?c=ScdUpTEfAZNEIPtaOzBBRAKyAnSuDbcS

**Comment by nonprofittechy** [comment]
I did a quick check on the production server and I see 1 completed interview on 1/21 and I was able to get to the download screen on that interview. There was one interview on 1/20 that was beyond the first step and that one also was at the download screen.

So if that person ran into this error, refreshing would have let them proceed. Unclear if this issue affected them or not.
